name: CI
on:
  push:
    branches:
      - 'version2'
      - 'feature/**'
jobs:
  php:
    name: PHP (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '8.0', '8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, dom, fileinfo
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Run PHP Unit Tests
        run: vendor/bin/phpunit
